namePrefix: prod-
resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 992382702050.dkr.ecr.ap-northeast-2.amazonaws.com/eks-demo-repo
  newTag: "18"
